In [17]:
# Tidy tuesday 9/27
# https://github.com/rfordatascience/tidytuesday/tree/master/data/2022/2022-09-27
# Location quotients (LQ) measure an artist occupation's concentration in the labor force, relative to the U.S. 
# labor force share. For example, an LQ of 1.2 indicates that the state's labor force in an occupation is 20 percent
# greater than the occupation's national labor force share. An LQ of 0.8 indicates that the state's labor force 
#in an occupation is 20 percent below the occupation's national labor force share.

import pandas as pd 
import numpy as np 
import plotly.express as px

In [2]:
artists = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-09-27/artists.csv")

In [22]:
artists.head(5)

3380

In [7]:
artists.count()

state                3380
race                 3380
type                 3380
all_workers_n        3380
artists_n            2681
artists_share        1926
location_quotient    1909
dtype: int64

In [35]:
counts_by_state = artists[["state", "artists_n"]]

counts_by_state = counts_by_state.dropna()

counts_by_state_grouped = counts_by_state.groupby(["state"]).sum()

counts_by_state_sorted = counts_by_state_grouped.sort_values(by="artists_n", ascending=False)

                      artists_n
state
California             445095.0
New York               243345.0
Texas                  166170.0
Florida                139335.0
Illinois                89355.0
Pennsylvania            79025.0
New Jersey              70045.0
Georgia                 66890.0
Ohio                    64315.0
Massachusetts           61770.0
Michigan                60620.0
Washington              60570.0
North Carolina          59560.0
Virginia                57620.0
Colorado                50570.0
Maryland                46560.0
Minnesota               44845.0
Tennessee               43035.0
Arizona                 41635.0
Oregon                  37480.0
Wisconsin               36700.0
Missouri                35815.0
Indiana                 31205.0
Connecticut             29705.0
Louisiana               25070.0
South Carolina          24710.0
Utah                    24005.0
Nevada                  23285.0
Alabama                 19940.0
Kentucky                18030.0
Kansas                  16900.0
Oklahoma                16815.0
Iowa                    15495.0
New Mexico              12175.0
District of Columbia    11915.0
Hawaii                  11535.0
Arkansas                11420.0
Nebraska                10510.0
Puerto Rico             10065.0
Maine                    8900.0
New Hampshire            8700.0
Idaho                    8655.0
Mississippi              8470.0
Rhode Island             8235.0
Montana                  6675.0
West Virginia            5950.0
Vermont                  5600.0
Delaware                 4515.0
South Dakota             3925.0
Alaska                   3598.0
North Dakota             3055.0
Wyoming                  2920.0